##### Creating an array

In [46]:
import numpy as np

In [47]:
x=np.array([20,85,33,78,92,14])
print(x)

[20 85 33 78 92 14]


In [48]:
type(x)

numpy.ndarray

In [49]:
x.ndim

1

In [50]:
x

array([20, 85, 33, 78, 92, 14])

In [52]:
x=np.array([20,85,33,78,92,14], dtype=np.int8)

In [53]:
x

array([20, 85, 33, 78, 92, 14], dtype=int8)

In [54]:
y=np.array([20,85,33,78,92,14], dtype=np.uint8)
y[0]=255

In [55]:
y

array([255,  85,  33,  78,  92,  14], dtype=uint8)

In [58]:
y=np.array([20,85,33,78,92,14], dtype=np.uint8)
y[0]=200

In [59]:
y

array([200,  85,  33,  78,  92,  14], dtype=uint8)

In [60]:
# to find y.size, y.shape, y.max(),y.std(),x.dtype,y.sum(),y.mean()

In [61]:
xx=np.array([10,20,22.63,86])

In [62]:
xx

array([10.  , 20.  , 22.63, 86.  ])

In [63]:
xx.dtype

dtype('float64')

In [66]:
x1=np.zeros(10,dtype=np.int16)
x1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [67]:
x2=np.ones(10,dtype=np.int16)
x2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [68]:
np.arange(10) #array of 10 elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x3=np.arange(4,20) #array of 4 to 20-1 elements
x3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
x4=np.arange(4,20,2) #array of 4 to 20 elements by increasing 2 
x4

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
#array operations
x4=np.arange(4,20,2) #array of 4 to 20 elements by increasing 2 
x5=np.arange(4,20,3) #array of 4 to 20 elements by increasing 2 
res1=x4*4
res2=x5/5
res3=2+x4
res4=10-x5

In [72]:
res1

array([16, 24, 32, 40, 48, 56, 64, 72])

In [73]:
res2

array([0.8, 1.4, 2. , 2.6, 3.2, 3.8])

In [74]:
res3

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
x6=[16, 24, 32, 40, 48, 56, 64, 72]*2

In [76]:
x6

[16, 24, 32, 40, 48, 56, 64, 72, 16, 24, 32, 40, 48, 56, 64, 72]

In [77]:
#vector operation can be done

In [79]:
#matrix :2dimentional array
M1=np.array([[1,4,7],[1,5,9],[10,1,3]])
M1

array([[ 1,  4,  7],
       [ 1,  5,  9],
       [10,  1,  3]])

In [82]:
r1=M1.dtype
r2=M1.shape
r4=M1.size
r5=M1.ndim

In [84]:
print(r1,r2,r4,r5)

int32 (3, 3) 9 2


In [86]:
M1[0:2,0:2]

array([[1, 4],
       [1, 5]])

In [87]:
M1.reshape(9,1)

array([[ 1],
       [ 4],
       [ 7],
       [ 1],
       [ 5],
       [ 9],
       [10],
       [ 1],
       [ 3]])

In [89]:
M1[0:2,0:2]=np.array([[1,0],[0,1]])
M1

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]])

In [90]:
M1.reshape(9,-1) #columns adjust accordingly
M1

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]])

In [91]:
xx1=M1.reshape(-1) #converts the data into vector
xx2=M1.flatten() #converts the data into vector
xx3=M1.T # transpose of a matrix
xx4=M1.min()
xx5=M1.min(axis=0) #minimum numbers in a row
xx6=M1.min(axis=1)# minimum number in a column

In [92]:
print(xx1,xx2,xx3,xx4,xx5,xx6)

[ 1  0  7  0  1  9 10  1  3] [ 1  0  7  0  1  9 10  1  3] [[ 1  0 10]
 [ 0  1  1]
 [ 7  9  3]] 0 [0 0 3] [0 0 1]


In [93]:
M1

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]])

In [94]:
M1.dtype

dtype('int32')

In [95]:
M2=M1.astype(np.int16)
M2

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]], dtype=int16)

In [96]:
M3=M1.astype(np.float16)
M3

array([[ 1.,  0.,  7.],
       [ 0.,  1.,  9.],
       [10.,  1.,  3.]], dtype=float16)

In [97]:
M4=M2

In [98]:
id(M4)

1782969581264

In [99]:
id(M2)

1782969581264

In [100]:
M4=M2.copy()
M4

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]], dtype=int16)

In [102]:
M4[0:3,0:1]=50

In [103]:
M4

array([[50,  0,  7],
       [50,  1,  9],
       [50,  1,  3]], dtype=int16)

In [104]:
M2

array([[ 1,  0,  7],
       [ 0,  1,  9],
       [10,  1,  3]], dtype=int16)

In [105]:
id(M4)

1782978427856

In [106]:
id(M2)

1782969581264