##### Day02:Tensorflow

In [46]:
import tensorflow as tf
import numpy as np

In [47]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [48]:
# create tensor

In [49]:
a=tf.constant([1,2,3,4])
b=tf.constant([8,10,15,9])
print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Tensor b: tf.Tensor([ 8 10 15  9], shape=(4,), dtype=int32)


In [50]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [51]:
a1=tf.constant([[1,2,3,4],[5,8,1,2],[4,1,6,9]])
b1=tf.constant([[8,10,15,3],[4,8,3,5],[10,12,8,6]])
print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Tensor b: tf.Tensor([ 8 10 15  9], shape=(4,), dtype=int32)


In [52]:
a2=tf.constant([[1,2,3,4],[5,8,1,2],[4,1,6,9]],dtype=np.int8)
b2=tf.constant([[8,10,15,12],[4,8,3,10],[1,4,6,9]],dtype=np.int8)
print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Tensor b: tf.Tensor([ 8 10 15  9], shape=(4,), dtype=int32)


In [53]:
# add tensors
c1=tf.add(a1,b1)
print("Addition of two tensor:",c1)

Addition of two tensor: tf.Tensor(
[[ 9 12 18  7]
 [ 9 16  4  7]
 [14 13 14 15]], shape=(3, 4), dtype=int32)


In [54]:
c2=tf.subtract(a2,b2)
print("Substraction of two tensor:",c2)

Substraction of two tensor: tf.Tensor(
[[ -7  -8 -12  -8]
 [  1   0  -2  -8]
 [  3  -3   0   0]], shape=(3, 4), dtype=int8)


In [61]:
a2-b2

<tf.Tensor: shape=(3, 4), dtype=int8, numpy=
array([[ -7,  -8, -12,  -8],
       [  1,   0,  -2,  -8],
       [  3,  -3,   0,   0]], dtype=int8)>

In [62]:
a1+b1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9, 12, 18,  7],
       [ 9, 16,  4,  7],
       [14, 13, 14, 15]])>

In [64]:
r2=a1*b1
print(r2)

tf.Tensor(
[[ 8 20 45 12]
 [20 64  3 10]
 [40 12 48 54]], shape=(3, 4), dtype=int32)


In [65]:
r3=a1/b1
print(r3)

tf.Tensor(
[[0.125      0.2        0.2        1.33333333]
 [1.25       1.         0.33333333 0.4       ]
 [0.4        0.08333333 0.75       1.5       ]], shape=(3, 4), dtype=float64)


In [66]:
r4=a1//b1
print(r4)

tf.Tensor(
[[0 0 0 1]
 [1 1 0 0]
 [0 0 0 1]], shape=(3, 4), dtype=int32)


In [60]:
#matrix multiplication
a3=tf.constant([[1,2],[2,7]])
a4=tf.constant([[1,0],[2,4]])
r5=tf.matmul(a3,a4)
print("Multiplication of two tensor:",r5)

Multiplication of two tensor: tf.Tensor(
[[ 5  8]
 [16 28]], shape=(2, 2), dtype=int32)
